const includedNames = [
  "Aragorn II Elessar",
  "Legolas",
  "Gimli",
  "Gandalf",
  "Saruman",
  "Frodo Baggins",
  "Samwise Gamgee",
  "Meriadoc Brandybuck",
  "Pippin Gamgee",
  "Boromir",
  "Faramir",
  "Elrond",
  "Arwen",
  "Celeborn",
  "Damrod",
  "Dwalin",
  "Bombur",
  "Balin",
  "Fíli and Kíli",
  "Dori",
  "Nori",
  "Ori",
  "Glóin",
  "Bifur",
  "Bofur",
  "Thorin II Oakenshield",
  "Dáin II Ironfoot",
  "Elendil",
  "Gil-galad",
  "Glorfindel",
  "Helm Hammerhand",
  "Háma",
  "The King of the Dead",
  "Thranduil",
  "Galadriel",
  "Éomer",
  "Durin",
  "Gollum",
  "Radagast",
  "Sauron",
  "Treebeard",
  "Witch-king of Angmar",
  "Mouth of Sauron",
  "Shelob",
  "Éowyn",
  "Haldir (Lorien)",
  "Mûmakil",
  "Ungoliant",
  "Shagrat",
  "Snaga",
  "Bolg",
  "Azog",
  "Sharku",
  "Gothmog",
  "Grishnákh",
  "Lugdush",
  "Uglúk",
  "Durin's Bane",
  "Gamling",
];
