export const DUMMY_CHARACTER = {
  _id: "5cd99d4bde30eff6ebccfc38",
  height: "3'1\"",
  race: "Hobbit",
  gender: "Male",
  birth: "22 September ,TA 2890",
  spouse: "None",
  death: "Unknown (Last sighting 29 SeptemberTA 3021,) (,SR 1421,)",
  realm: "The Shire",
  hair: "Brown, later white",
  name: "Bilbo Baggins",
  wikiUrl: "http://lotr.wikia.com//wiki/Bilbo_Baggins",
  mainAttack: {
    disabledTurns: 0,
    disabledFor: 2,
    name: "Sting",
    value: 30,
  },
  specialAttack: {
    disabledTurns: 0,
    disabledFor: 7,
    name: "Sneak",
    value: 70,
    isSpecial: true,
  },
  health: 250,
};

export const DUMMY_ENEMY = [
  {
    _id: "5cd99d4bde30eff6ebccfc38",
    height: "3'1\"",
    race: "Hobbit",
    gender: "Male",
    birth: "22 September ,TA 2890",
    spouse: "None",
    death: "Unknown (Last sighting 29 SeptemberTA 3021,) (,SR 1421,)",
    realm: "The Shire",
    hair: "Brown, later white",
    name: "Bilbo Baggins",
    wikiUrl: "http://lotr.wikia.com//wiki/Bilbo_Baggins",
    mainAttack: {
      disabledTurns: 0,
      disabledFor: 2,
      name: "Sting",
      value: 30,
    },
    specialAttack: {
      disabledTurns: 0,
      disabledFor: 7,
      name: "Sneak",
      value: 70,
      isSpecial: true,
    },
    health: 250,
  },
  {
    _id: "5cd99d4bde30eff6ebccfc3a",
    height: "6'0\"",
    race: "Human",
    gender: "Male",
    birth: "Late ,Third Age",
    spouse: "",
    death: "March 15 ,3019",
    realm: "Harad",
    hair: "",
    name: "Black Serpent",
    wikiUrl: "http://lotr.wikia.com//wiki/Black_Serpent",
    mainAttack: {
      disabledTurns: 0,
      disabledFor: 2,
      name: "Standard Bearer",
      value: 20,
    },
    specialAttack: {
      disabledTurns: 0,
      disabledFor: 7,
      name: "Mûmakil",
      value: 140,
      isSpecial: true,
    },
    health: 380,
  },
  {
    _id: "5cd99d4bde30eff6ebccfc4f",
    height: "4'8\"",
    race: "Dwarf",
    gender: "Male",
    birth: "TA 2843",
    spouse: "",
    death: "",
    realm: "Blue Mountains",
    hair: "Dark Brown (films)",
    name: "Bofur",
    wikiUrl: "http://lotr.wikia.com//wiki/Bofur",
    mainAttack: {
      disabledTurns: 0,
      disabledFor: 2,
      name: "Warhammer",
      value: 25,
    },
    specialAttack: {
      disabledTurns: 0,
      disabledFor: 7,
      name: "Dwarven Power",
      value: 25,
      isSpecial: true,
    },
    health: 250,
  },
  {
    _id: "5cd99d4bde30eff6ebccfc54",
    height: "4'5\"",
    race: "Dwarf",
    gender: "Male",
    birth: "TA 2834",
    spouse: "",
    death: "",
    realm: "Erebor",
    hair: "Ginger",
    name: "Bombur",
    wikiUrl: "http://lotr.wikia.com//wiki/Bombur",
    mainAttack: {
      disabledTurns: 0,
      disabledFor: 2,
      name: "Flail",
      value: 25,
    },
    specialAttack: {
      disabledTurns: 0,
      disabledFor: 7,
      name: "Dwarven Power",
      value: 25,
      isSpecial: true,
    },
    health: 230,
  },
  {
    _id: "5cd99d4bde30eff6ebccfc57",
    height: "6'4\"",
    race: "Human",
    gender: "Male",
    birth: "TA 2978",
    spouse: "",
    death: "February 26 ,3019",
    realm: "Gondor",
    hair: "Dark (book) Light brown (movie)",
    name: "Boromir",
    wikiUrl: "http://lotr.wikia.com//wiki/Boromir",
    mainAttack: {
      disabledTurns: 0,
      disabledFor: 2,
      name: "Broadsword",
      value: 50,
    },
    specialAttack: {
      disabledTurns: 0,
      disabledFor: 7,
      name: "Horn of Gondor",
      value: 150,
      isSpecial: true,
    },
    health: 410,
  },
];

export const DUMMY_TEAM = [
  {
    _id: "5cd99d4bde30eff6ebccfbe6",
    height: "6'6\"",
    race: "Human",
    gender: "Male",
    birth: "March 1 ,2931",
    spouse: "Arwen",
    death: "FO 120",
    realm: "Arnor, Gondor",
    hair: "Dark",
    name: "Aragorn II Elessar",
    wikiUrl: "http://lotr.wikia.com//wiki/Aragorn_II_Elessar",
    mainAttack: {
      disabledTurns: 0,
      disabledFor: 2,
      name: "Andúril",
      value: 50,
    },
    specialAttack: {
      disabledTurns: 0,
      disabledFor: 7,
      name: "Army of the Dead",
      value: 200,
      isSpecial: true,
    },
    health: 500,
  },
  {
    _id: "5cd99d4bde30eff6ebccfc07",
    height: "5'10\"",
    race: "Elf",
    gender: "Female",
    birth: "TA 241",
    spouse: "Aragorn II Elessar",
    death: "FO 121",
    realm: "Rivendell",
    hair: "Black",
    name: "Arwen",
    wikiUrl: "http://lotr.wikia.com//wiki/Arwen",
    mainAttack: {
      disabledTurns: 0,
      disabledFor: 2,
      name: "Hadhafang",
      value: 35,
    },
    specialAttack: {
      disabledTurns: 0,
      disabledFor: 7,
      name: "Flood",
      value: 140,
      isSpecial: true,
    },
    health: 280,
  },
  {
    _id: "5cd99d4bde30eff6ebccfc15",
    height: "3'6\"",
    race: "Hobbit",
    gender: "Male",
    birth: "22 September ,TA 2968",
    spouse: "",
    death: "Unknown (Last sighting ,September 29 ,3021,) (,SR 1421,)",
    realm: "The Shire",
    hair: "Brown",
    name: "Frodo Baggins",
    wikiUrl: "http://lotr.wikia.com//wiki/Frodo_Baggins",
    mainAttack: {
      disabledTurns: 0,
      disabledFor: 2,
      name: "Sting",
      value: 30,
    },
    specialAttack: {
      disabledTurns: 0,
      disabledFor: 7,
      name: "Invisibilty",
      value: 130,
      isSpecial: true,
    },
    health: 220,
  },
  {
    _id: "5cd99d4bde30eff6ebccfc1b",
    height: "4'6\"",
    race: "Dwarf",
    gender: "Male",
    birth: "TA 2763",
    spouse: "",
    death: "TA 2994",
    realm: "Erebor",
    hair: "White",
    name: "Balin",
    wikiUrl: "http://lotr.wikia.com//wiki/Balin",
    mainAttack: {
      disabledTurns: 0,
      disabledFor: 2,
      name: "Balin's Axe",
      value: 30,
    },
    specialAttack: {
      disabledTurns: 0,
      disabledFor: 7,
      name: "Dwarven Power",
      value: 25,
      isSpecial: true,
    },
    health: 260,
  },
  {
    _id: "5cd99d4bde30eff6ebccfc37",
    height: "4'5\"",
    race: "Dwarf",
    gender: "Male",
    birth: "TA 2814",
    spouse: "",
    death: "UnknownFourth Age",
    realm: "Blue Mountains",
    hair: "Black/ Grey (film)",
    name: "Bifur",
    wikiUrl: "http://lotr.wikia.com//wiki/Bifur",
    mainAttack: {
      disabledTurns: 0,
      disabledFor: 2,
      name: "Boar spear",
      value: 25,
    },
    specialAttack: {
      disabledTurns: 0,
      disabledFor: 7,
      name: "Dwarven Power",
      value: 25,
      isSpecial: true,
    },
    health: 250,
  },
];
